#!/bin/bash

# I'm lazy, and it's easier to remember './scripts/run' than the entire flatpak command
EXTRA_ARGS=
if [[ "$1" == "--debug" ]]; then
    EXTRA_ARGS="--env=GTK_DEBUG=interactive"
fi
if [[ "$1" == "--inspect" ]]; then
    EXTRA_ARGS="--command=sh --devel"
fi
flatpak run --env=G_MESSAGES_DEBUG=all $EXTRA_ARGS com.github.avojak.warble ${@:2}